export type Database = {
    public: {
        Tables: {
            patients: {
                Row: {
                    id: string;
                    no_patient: string | null;
                    no_avs: string | null;
                    titre: string | null;
                    titre_courtoisie: string | null;
                    nom: string | null;
                    prenom: string | null;
                    adresse_compl: string | null;
                    rue: string | null;
                    npa: string | null;
                    localite: string | null;
                    tel1: string | null;
                    no_tel1: string | null;
                    tel2: string | null;
                    no_tel2: string | null;
                    tel3: string | null;
                    no_tel3: string | null;
                    ddn: string | null;
                    langue: string | null;
                    nationalite: string | null;
                    dob: string | null;
                    date_deces: string | null;
                    employeur: string | null;
                    profession: string | null;
                    etat_civil: string | null;
                    nom_jeune_fille: string | null;
                    medecin_traitant: string | null;
                    sexe: string | null;
                    genre: string | null;
                    pays: string | null;
                    coord: string | null;
                    email: string | null;
                    notification_sms: string | null;
                    debiteur: string | null;
                    contact: string | null;
                    representant_legal: string | null;
                    commentaire: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    no_patient?: string | null;
                    no_avs?: string | null;
                    titre?: string | null;
                    titre_courtoisie?: string | null;
                    nom?: string | null;
                    prenom?: string | null;
                    adresse_compl?: string | null;
                    rue?: string | null;
                    npa?: string | null;
                    localite?: string | null;
                    tel1?: string | null;
                    no_tel1?: string | null;
                    tel2?: string | null;
                    no_tel2?: string | null;
                    tel3?: string | null;
                    no_tel3?: string | null;
                    ddn?: string | null;
                    langue?: string | null;
                    nationalite?: string | null;
                    dob?: string | null;
                    date_deces?: string | null;
                    employeur?: string | null;
                    profession?: string | null;
                    etat_civil?: string | null;
                    nom_jeune_fille?: string | null;
                    medecin_traitant?: string | null;
                    sexe?: string | null;
                    genre?: string | null;
                    pays?: string | null;
                    coord?: string | null;
                    email?: string | null;
                    notification_sms?: string | null;
                    debiteur?: string | null;
                    contact?: string | null;
                    representant_legal?: string | null;
                    commentaire?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    no_patient?: string | null;
                    no_avs?: string | null;
                    titre?: string | null;
                    titre_courtoisie?: string | null;
                    nom?: string | null;
                    prenom?: string | null;
                    adresse_compl?: string | null;
                    rue?: string | null;
                    npa?: string | null;
                    localite?: string | null;
                    tel1?: string | null;
                    no_tel1?: string | null;
                    tel2?: string | null;
                    no_tel2?: string | null;
                    tel3?: string | null;
                    no_tel3?: string | null;
                    ddn?: string | null;
                    langue?: string | null;
                    nationalite?: string | null;
                    dob?: string | null;
                    date_deces?: string | null;
                    employeur?: string | null;
                    profession?: string | null;
                    etat_civil?: string | null;
                    nom_jeune_fille?: string | null;
                    medecin_traitant?: string | null;
                    sexe?: string | null;
                    genre?: string | null;
                    pays?: string | null;
                    coord?: string | null;
                    email?: string | null;
                    notification_sms?: string | null;
                    debiteur?: string | null;
                    contact?: string | null;
                    representant_legal?: string | null;
                    commentaire?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            appointments: {
                Row: {
                    id: string;
                    patient_id: string;
                    date: string | null;
                    status: string | null;
                    duration: number | null;
                    event_name: string | null;
                    contact: string | null;
                    centre: string | null;
                    practitioner: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    patient_id: string;
                    date?: string | null;
                    status?: string | null;
                    duration?: number | null;
                    event_name?: string | null;
                    contact?: string | null;
                    centre?: string | null;
                    practitioner?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    patient_id?: string;
                    date?: string | null;
                    status?: string | null;
                    duration?: number | null;
                    event_name?: string | null;
                    contact?: string | null;
                    centre?: string | null;
                    practitioner?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            invoices: {
                Row: {
                    id: string;
                    patient_id: string;
                    patient_avs: string | null;
                    centre: string | null;
                    date: string | null;
                    invoice_number: string | null;
                    no_assured_person: string | null;
                    reimbursment_type: string | null;
                    law: string | null;
                    treatment_type: string | null;
                    no_assured_card: string | null;
                    treatment_start_date: string | null;
                    treatment_end_date: string | null;
                    prestation_location: string | null;
                    prescribing_doctor: string | null;
                    prescribing_doctor_address: string | null;
                    total_amount: number | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    patient_id: string;
                    patient_avs?: string | null;
                    centre?: string | null;
                    date?: string | null;
                    invoice_number?: string | null;
                    no_assured_person?: string | null;
                    reimbursment_type?: string | null;
                    law?: string | null;
                    treatment_type?: string | null;
                    no_assured_card?: string | null;
                    treatment_start_date?: string | null;
                    treatment_end_date?: string | null;
                    prestation_location?: string | null;
                    prescribing_doctor?: string | null;
                    prescribing_doctor_address?: string | null;
                    total_amount?: number | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    patient_id?: string;
                    patient_avs?: string | null;
                    centre?: string | null;
                    date?: string | null;
                    invoice_number?: string | null;
                    no_assured_person?: string | null;
                    reimbursment_type?: string | null;
                    law?: string | null;
                    treatment_type?: string | null;
                    no_assured_card?: string | null;
                    treatment_start_date?: string | null;
                    treatment_end_date?: string | null;
                    prestation_location?: string | null;
                    prescribing_doctor?: string | null;
                    prescribing_doctor_address?: string | null;
                    total_amount?: number | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            services: {
                Row: {
                    id: string;
                    invoice_id: string;
                    date: string | null;
                    number: number | null;
                    position_number: string | null;
                    description: string | null;
                    unit_value: number | null;
                    pt_nbr: number | null;
                    pt_value: number | null;
                    amount: number | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    invoice_id: string;
                    date?: string | null;
                    number?: number | null;
                    position_number?: string | null;
                    description?: string | null;
                    unit_value?: number | null;
                    pt_nbr?: number | null;
                    pt_value?: number | null;
                    amount?: number | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    invoice_id?: string;
                    date?: string | null;
                    number?: number | null;
                    position_number?: string | null;
                    description?: string | null;
                    unit_value?: number | null;
                    pt_nbr?: number | null;
                    pt_value?: number | null;
                    amount?: number | null;
                    created_at?: string;
                };
            };
        };
        Views: {
            [_ in never]: never;
        };
        Functions: {
            [_ in never]: never;
        };
        Enums: {
            [_ in never]: never;
        };
        CompositeTypes: {
            [_ in never]: never;
        };
    };
};
